version: '2'
services:
    examen2-app:
        image: examen2
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://examen2-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=examen2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    examen2-mongodb:
        extends:
            file: mongodb.yml
            service: examen2-mongodb
